# -*- coding: utf-8 -*-
"""ada.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pCDm2xVm6VgeYOhTbh3BGkhX2lSNyQLU
"""

from google.colab import drive
drive.mount('/content/drive')
# pd.read_csv("/content/drive/MyDrive/ada/d1.csv")

import pandas as pd

fulldata = pd.read_csv("/content/drive/MyDrive/ada/d1.csv")
print("FULL DATA FRAME")
print(fulldata.info)



df = pd.read_csv("/content/drive/MyDrive/ada/d1.csv")

# Display basic information about the DataFrame
print("Basic Information about the DataFrame:")
print(df.info())

# Check for missing values in each column
missing_values = df.isnull().sum()
print("\nMissing Values in Each Column:")
print(missing_values)

# Display percentage of missing values in each column
percentage_missing = (missing_values / len(df)) * 100
print("\nPercentage of Missing Values in Each Column:")
print(percentage_missing)

# Drop rows with missing values (if needed)
# df_cleaned = df.dropna()

# Fill missing values with a specific value or strategy (if needed)
# df_filled = df.fillna(value)

# Display basic statistics of the DataFrame
print("\nBasic Statistics of the DataFrame:")
print(df.describe())

# Additional analytics or operations can be performed as needed

# Save the cleaned DataFrame to a new CSV file (if needed)
# df_cleaned.to_csv('cleaned_data.csv', index=False)